[project]
name = "repl-nix-web3cryptorag"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain-chroma>=0.1.4",
    "langchain-huggingface>=0.1.2",
    "python-dotenv>=1.0.1",
]
